// <auto-generated />
using System;
using Iurec_Alexandra_Proiect_Master.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Iurec_Alexandra_Proiect_Master.Migrations
{
    [DbContext(typeof(BeautySalonContext))]
    [Migration("20211220140435_ExtendedModel")]
    partial class ExtendedModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BeautyServiceID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.HasKey("AppointmentID");

                    b.HasIndex("BeautyServiceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.BeautyService", b =>
                {
                    b.Property<int>("BeautyServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeautyServiceID");

                    b.ToTable("BeautyService");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.BookedEquipment", b =>
                {
                    b.Property<int>("BeautyServiceID")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.HasKey("BeautyServiceID", "EquipmentID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("BookedEquipment");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Producer")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("EquipmentID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.Appointment", b =>
                {
                    b.HasOne("Iurec_Alexandra_Proiect_Master.Models.BeautyService", "BeautyService")
                        .WithMany("Appointments")
                        .HasForeignKey("BeautyServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iurec_Alexandra_Proiect_Master.Models.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeautyService");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.BookedEquipment", b =>
                {
                    b.HasOne("Iurec_Alexandra_Proiect_Master.Models.BeautyService", "BeautyService")
                        .WithMany("BookedEquipments")
                        .HasForeignKey("BeautyServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iurec_Alexandra_Proiect_Master.Models.Equipment", "Equipment")
                        .WithMany("BookedEquipments")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeautyService");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.BeautyService", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BookedEquipments");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.Employee", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Iurec_Alexandra_Proiect_Master.Models.Equipment", b =>
                {
                    b.Navigation("BookedEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
